name: Android Emulator in Docker

on:
  push:
    branches: [main]

jobs:
  android-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # 1️⃣ Instalar Docker (se ainda não estiver)
      - name: Setup Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          docker --version

      # 2️⃣ Rodar container Android com VNC e ADB
      - name: Start Android Docker
        run: |
          docker pull budtmo/docker-android-x86-11.0
          docker run -d --name android-emulator \
            -p 6080:6080 -p 5555:5555 \
            -e DEVICE="pixel" \
            -e EMULATOR_ARGS="-no-window -no-audio -no-boot-anim" \
            budtmo/docker-android-x86-11.0

          # Esperar o emulador iniciar
          echo "Esperando 60s para o emulador iniciar..."
          sleep 60

      # 3️⃣ Instalar APK
      - name: Install APK
        run: |
          wget https://github.com/appium/android-apidemos/releases/download/v3.1.0/ApiDemos-debug.apk -O ApiDemos-debug.apk
          docker exec android-emulator adb install -r /github/workspace/ApiDemos-debug.apk

      # 4️⃣ Abrir o app
      - name: Launch App
        run: docker exec android-emulator adb shell am start -n io.appium.android.apis/.ApiDemos

      # 5️⃣ Tirar screenshot
      - name: Capture Screenshot
        run: docker exec android-emulator adb exec-out screencap -p > screen1.png

      # 6️⃣ Upload screenshot como artifact
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-screenshots
          path: screen1.png
