name: Appetize Android Bot Headless v2

on:
  push:
    branches: [main]

jobs:
  appetize-bot:
    runs-on: ubuntu-latest

    env:
      APPETIZE_KEY: "tok_j5qqrpvbvr5zureqtco7e22z54"  # token válido só para criar sessão
      APP_ID: "b_62au3skfbffay5jcys3ymiru2e"  # appId do APK já carregado manualmente
      APP_PACKAGE: "io.appium.android.apis"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # 1️⃣ Criar sessão diretamente
      - name: Create Appetize Session
        id: session
        run: |
          SESSION=$(curl -s -X POST "https://api.appetize.io/v1/sessions" \
              -H "Authorization: Bearer $APPETIZE_KEY" \
              -d "{\"appId\":\"$APP_ID\"}")
          SESSION_ID=$(echo "$SESSION" | jq -r '.uuid // empty')
          if [ -z "$SESSION_ID" ]; then
            echo "❌ Falha ao criar sessão Appetize. Resposta: $SESSION"
            exit 1
          fi
          echo "SESSION_ID=$SESSION_ID" >> $GITHUB_ENV
          echo "✅ Sessão criada com sucesso: $SESSION_ID"

      # 2️⃣ Esperar o app iniciar
      - name: Wait for App Launch
        run: sleep 15

      # 3️⃣ Interações automáticas
      - name: Interact with App
        run: |
          random_sleep() { sleep $(( (RANDOM % 5) + 2 )); }

          # Tap exemplo
          curl -X POST "https://api.appetize.io/v1/sessions/$SESSION_ID/touch" \
               -H "Authorization: Bearer $APPETIZE_KEY" \
               -d '{"x":300,"y":800,"type":"down"}'
          curl -X POST "https://api.appetize.io/v1/sessions/$SESSION_ID/touch" \
               -H "Authorization: Bearer $APPETIZE_KEY" \
               -d '{"x":300,"y":800,"type":"up"}'
          random_sleep

          # Swipe exemplo
          curl -X POST "https://api.appetize.io/v1/sessions/$SESSION_ID/swipe" \
               -H "Authorization: Bearer $APPETIZE_KEY" \
               -d '{"startX":300,"startY":1200,"endX":300,"endY":400,"duration":500}'
          random_sleep

      # 4️⃣ Captura de screenshot
      - name: Capture Screenshot
        run: |
          curl -X GET "https://api.appetize.io/v1/sessions/$SESSION_ID/screenshot" \
               -H "Authorization: Bearer $APPETIZE_KEY" \
               -o screen1.png

      # 5️⃣ Upload artifacts
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: appetize-artifacts
          path: screen1.png
