name: Appetize Android Headless Test

on:
  push:
    branches: [main]

jobs:
  appetize-test:
    runs-on: ubuntu-latest

    env:
      APPETIZE_KEY: "tok_j5qqrpvbvr5zureqtco7e22z54" # coloque sua chave Appetize aqui
      APP_PACKAGE: "io.appium.android.apis"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # 1️⃣ Baixar APK de exemplo (ApiDemos)
      - name: Download Example APK
        run: |
          wget https://github.com/appium/android-apidemos/releases/download/v3.1.0/ApiDemos-debug.apk -O ./ApiDemos-debug.apk

      # 2️⃣ Upload APK para Appetize (opcional se já estiver online)
      - name: Upload APK to Appetize
        run: |
          curl -F "file=@./ApiDemos-debug.apk" \
               -F "platform=android" \
               -H "Authorization: Bearer $APPETIZE_KEY" \
               https://api.appetize.io/v1/upload

      # 3️⃣ Interações via API
      - name: Send Commands to Appetize
        run: |
          # Tap simulando clique na tela
          curl -X POST "https://api.appetize.io/v1/sessions/<SESSION_ID>/touch" \
               -H "Authorization: Bearer $APPETIZE_KEY" \
               -d '{"x":300,"y":800,"type":"down"}'
          sleep 2
          curl -X POST "https://api.appetize.io/v1/sessions/<SESSION_ID>/touch" \
               -H "Authorization: Bearer $APPETIZE_KEY" \
               -d '{"x":300,"y":800,"type":"up"}'

      # 4️⃣ Captura de screenshot
      - name: Capture Screenshot
        run: |
          curl -X GET "https://api.appetize.io/v1/sessions/<SESSION_ID>/screenshot" \
               -H "Authorization: Bearer $APPETIZE_KEY" \
               -o screen1.png

      # 5️⃣ Upload artifacts
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: appetize-artifacts
          path: screen1.png
