name: Android Headless CI

on:
  push:
    branches: [main]

jobs:
  android-emulator:
    runs-on: ubuntu-latest

    env:
      ANDROID_HOME: /usr/local/android-sdk
      PATH: ${{ env.ANDROID_HOME }}/cmdline-tools/latest/bin:${{ env.ANDROID_HOME }}/platform-tools:${{ env.PATH }}
      EMULATOR_NAME: test_emulator
      DEVICE: "pixel"
      API_LEVEL: 33

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # 1️⃣ Instalar Android SDK
      - name: Setup Android SDK
        run: |
          sudo mkdir -p $ANDROID_HOME
          sudo chown $USER:$USER $ANDROID_HOME
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d $ANDROID_HOME
          mv $ANDROID_HOME/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
          yes | sdkmanager --sdk_root=$ANDROID_HOME "platform-tools" "platforms;android-$API_LEVEL" "system-images;android-$API_LEVEL;google_apis;x86_64" "emulator"

      # 2️⃣ Criar e iniciar o emulador headless
      - name: Create & Start Emulator
        run: |
          echo "no" | avdmanager create avd -n $EMULATOR_NAME -k "system-images;android-$API_LEVEL;google_apis;x86_64" -d $DEVICE --force
          $ANDROID_HOME/emulator/emulator -avd $EMULATOR_NAME -no-window -no-audio -no-boot-anim &
          # Esperar o emulador inicializar
          adb wait-for-device
          boot_completed=""
          until [[ "$boot_completed" == "1" ]]; do
            boot_completed=$(adb shell getprop sys.boot_completed 2>/dev/null | tr -d '\r')
            sleep 5
          done

      # 3️⃣ Instalar APK
      - name: Install APK
        run: |
          wget https://github.com/appium/android-apidemos/releases/download/v3.1.0/ApiDemos-debug.apk -O ApiDemos-debug.apk
          adb install -r ApiDemos-debug.apk

      # 4️⃣ Abrir o app
      - name: Launch App
        run: adb shell am
